### ISSUE TITLE
(ahk_x11:3498): GLib-GObject-CRITICAL when running installer without arg

### ISSUE THREAD

**Issue by phaleth** [phil294/AHK_X11#11] opened 2022-10-02 10:08 UTC
Turns out there is some kind of REPL that represents a command line tool.

I've installed ahk from CLI using the installer from the zip file release of version 0.2.0 and got the following error after which ahk jumps out of the REPL.

If ahk file is provided as arg the REPL starts up without error.

```sh
user@debian:$ ./ahk_x11 
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11> 
(ahk_x11:3498): GLib-GObject-CRITICAL **: 11:22:49.425: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
user@debian:$ touch test.ahk
user@debian:$ ./ahk_x11 test.ahk
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11> MsgBox, Hello
ahk_x11> 
```

```sh
user@debian:$ uname -a
Linux debian 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
```

**Comment by phil294** [comment] 2022-10-02 10:28
Running the program without args should always open up the graphical installer, no matter what. It should not matter whether it's cli or lauched via click.

> I've installed ahk from CLI using the installer

so this means the graphical installer *worked*, but only once? And the second time you run it, it crashes, no matter if cli or graphical? Not sure how that is possible.

Tbf, if you only want the repl, you should  run it as `./ahk_x11 --repl` as indicated in the Readme, but I'm still not sure if this is quite the best design... it just seems very convenient to be able to run the installer and run scripts with the same binary  (in contrary to win ahk, where this is  provided by two different exes)

**Comment by phaleth** [comment] 2022-10-02 11:06
I wasn't aware of the REPL and the `--repl` flag. I know I should read the README, but anyways. The installer worked fine with a GUI window popping up, but at the same time when the GUI window showed up that error showed up in CLI as well which made CLI exit outta REPL.

So right now I think the problem is that REPL is started even without the `--repl` flag and I agree with you that the same binary should be able to install ahk and also run ahk scripts and also run the REPL. :smile:

**Comment by phil294** [comment] 2022-10-02 19:43
Could you please tell me your Gtk version? `dpkg -l libgtk-3-0`

> So right now I think the problem is that REPL is started even without the --repl flag 

while that may not seem intuitive, this is actually being done on purpose: Every script, once its auto execute section finishes, opens up a repl. This includes scripts passed via command line, the installer (no script), and also `--repl` which internally is the same as running a script with just `#Persistent` in it.

This might help debugging scripts and there are no real drawbacks I can see.

Now for why the installer fails on your system... I have no idea and I could not reproduce that. I assume it is related to your setup: Debian/MATE. Debugging this in a VM seems like an overkill for such a minor issue, so let's just ignore this for now.

On the other hand, if you *want* to find out why it fails, you could either dig around with the [debug build](https://github.com/phil294/AHK_X11/releases/download/0.2.0/ahk_x11-DEBUG.zip) with GDB or download the [installer.ahk](https://github.com/phil294/AHK_X11/blob/master/src/installer.ahk), pass it manually as a script and find out which line makes the repl fail. Most likely, it's the first `Gui` line anyway (`GLib-GObject-CRITICAL` means it is Gtk-related) so this won't help much, so I suggest you ignore all of what I wrote above.

**Comment by phaleth** [comment] 2022-10-03 16:54
Sorry, I guess I totally didn't describe the issue from a good end.

The installer worked fine even for the first time when I executed `./ahk_x11` and even with the error showing up in CLI.

The only thing that went wrong was that the CLI jumped outta REPL as shown in the original post of this issue. After the ahk installation is done the REPL works just fine.

I guess you understand now how the error happened. I don't know how the installation process works, but I think it just ran the REPL before the REPL was installed and that resulted in the error. Sure this is such a minor issue I just thought putting it here for the sake of posterity.

```sh
user@debian:$ dpkg -l libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version           Architecture Description
+++-================-=================-============-====================================
ii  libgtk-3-0:amd64 3.24.24-4+deb11u2 amd64        GTK graphical user interface library
```

**Comment by phil294** [comment] 2022-10-27 11:54
Ok, I see.

> I think it just ran the REPL before the REPL was installed 

No that is not possible, there is no repl install process, it just, well, starts when it starts. 

I'm still pretty sure it's some exotic mate+gtk+stdin combination problem (that I cannot reproduce), and also since doesn't really break anything, I'll close this for now.

Thank you!

**Closed by phil294** 2022-10-27 11:54 UTC

**Comment by phaleth** [comment] 2023-02-27 17:12
For the sake of posterity. With the 0.5.0 release I got the following.

```sh
user@debian:$ chmod +x ./ahk_x11-0.5.0-x86_64.AppImage
user@debian:$ ./ahk_x11-0.5.0-x86_64.AppImage
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
Starting graphical installer. Please see --help for more options.

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:00.112: ../../../../gobject/gvalue.c:188: cannot initialize GValue with type 'GEnum', this type is abstract with regards to GValue use, use a more specific (derived) type

(AppRun.wrapped:3802): GLib-GObject-CRITICAL **: 18:02:00.112: g_value_set_enum: assertion 'G_VALUE_HOLDS_ENUM (value)' failed

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:00.112: ../../../../gobject/gtype.c:4266: type id '0' is invalid

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:00.112: can't peek value table for type '<invalid>' which is not currently referenced

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:00.112: ../../../../gobject/gvalue.c:188: cannot initialize GValue with type '(null)', this type has no GTypeValueTable implementation

(AppRun.wrapped:3802): GLib-GObject-CRITICAL **: 18:02:00.113: g_value_copy: assertion 'G_IS_VALUE (src_value)' failed

(AppRun.wrapped:3802): GLib-GObject-CRITICAL **: 18:02:00.116: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:00.116: unable to set property 'window-position' of type 'GtkWindowPosition' from value of type '(null)'

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:04.303: ../../../../gobject/gvalue.c:188: cannot initialize GValue with type 'GEnum', this type is abstract with regards to GValue use, use a more specific (derived) type

(AppRun.wrapped:3802): GLib-GObject-CRITICAL **: 18:02:04.303: g_value_set_enum: assertion 'G_VALUE_HOLDS_ENUM (value)' failed

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:04.304: ../../../../gobject/gtype.c:4266: type id '0' is invalid

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:04.304: can't peek value table for type '<invalid>' which is not currently referenced

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:04.304: ../../../../gobject/gvalue.c:188: cannot initialize GValue with type '(null)', this type has no GTypeValueTable implementation

(AppRun.wrapped:3802): GLib-GObject-CRITICAL **: 18:02:04.304: g_value_copy: assertion 'G_IS_VALUE (src_value)' failed

(AppRun.wrapped:3802): GLib-GObject-CRITICAL **: 18:02:04.306: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(AppRun.wrapped:3802): GLib-GObject-WARNING **: 18:02:04.306: unable to set property 'buttons' of type 'GtkButtonsType' from value of type '(null)'
Gtk-Message: 18:02:04.419: GtkDialog mapped without a transient parent. This is discouraged.
user@debian:$ ./ahk_x11-0.5.0-x86_64.AppImage test.ahk
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11> MsgBox, hello
ahk_x11> 
(AppRun.wrapped:3877): GLib-GObject-WARNING **: 18:02:58.979: ../../../../gobject/gvalue.c:188: cannot initialize GValue with type 'GEnum', this type is abstract with regards to GValue use, use a more specific (derived) type

(AppRun.wrapped:3877): GLib-GObject-CRITICAL **: 18:02:58.979: g_value_set_enum: assertion 'G_VALUE_HOLDS_ENUM (value)' failed

(AppRun.wrapped:3877): GLib-GObject-WARNING **: 18:02:58.987: ../../../../gobject/gtype.c:4266: type id '0' is invalid

(AppRun.wrapped:3877): GLib-GObject-WARNING **: 18:02:58.987: can't peek value table for type '<invalid>' which is not currently referenced

(AppRun.wrapped:3877): GLib-GObject-WARNING **: 18:02:58.987: ../../../../gobject/gvalue.c:188: cannot initialize GValue with type '(null)', this type has no GTypeValueTable implementation

(AppRun.wrapped:3877): GLib-GObject-CRITICAL **: 18:02:58.987: g_value_copy: assertion 'G_IS_VALUE (src_value)' failed

(AppRun.wrapped:3877): GLib-GObject-CRITICAL **: 18:02:59.001: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed

(AppRun.wrapped:3877): GLib-GObject-WARNING **: 18:02:59.001: unable to set property 'buttons' of type 'GtkButtonsType' from value of type '(null)'
Gtk-Message: 18:02:59.181: GtkDialog mapped without a transient parent. This is discouraged.
^C
user@debian:$ cat /etc/issue
Debian GNU/Linux 11 \n \l
user@debian:$ dpkg -l libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version           Architecture Description
+++-================-=================-============-====================================
ii  libgtk-3-0:amd64 3.24.24-4+deb11u2 amd64        GTK graphical user interface library
```

The MsgBox has popped up.
