### ISSUE TITLE
Send %clipboard% sends symbols instead of numbers

### ISSUE THREAD

**Issue by SmartManoj** [phil294/AHK_X11#22] opened 2022-11-27 03:11 UTC
Copy 123 to the clipboard. The following snippets send `!@#` instead of  `123`

`::cb::%clipboard%`

Failed workaround
```::cb::
Send {Shift Down}
Send %clipboard%
Send {Shift Up}
Return
```

`MsgBox, %Clipboard%` works fine.

**Comment by phil294** [comment] 2022-11-27 23:17
thanks for the report!

actually has nothing to do with clipboard, just `send 123` falsely presses shift key.

will be fixed with the next release in just a few days.

**Comment by phil294** [comment] 2022-12-13 23:55
fixed

**Closed by phil294** 2022-12-13 23:55 UTC

**Comment by SmartManoj** [comment] 2023-02-18 02:29
`send 123@`
Outputs 1232
Seems you disabled pressing shift?
Also please mention the commit it was fixed.

**Comment by phil294** [comment] 2023-02-18 16:22
this is same as #32

the problem is, shift is not disabled, but it needs to be detected on a per-character basis. When the string is `A`, we can detect that this is indeed an upper case letter and thus shift should be included in the modifiers for this key. But when it's `@`, this is not so easy to detect. Surely not too hard to figure out though. I'm working on a few other things right now, so I can't say yet when I will get to it

As to where this was fixed: [This line](https://github.com/phil294/AHK_X11/commit/2304673a6651896271c2a837ab57bde41edbf57e#diff-cfadc7ddfb2cf1c989680ef35031098d000d16070dc7bef50238975a01818bbaR113), I think. There have been a few other changes to that logic afterwards, https://github.com/phil294/AHK_X11/commit/4229362e71f7e011953b61d6c1dacf70bae90efd and https://github.com/phil294/AHK_X11/commit/141d20d8be782ac68906164edf1a912453a91972
